import ManagedObject, { $ManagedObjectSettings } from "sap/ui/base/ManagedObject";
import BusyIndicator from "sap/ui/core/BusyIndicator";
import ValidateException from "sap/ui/model/ValidateException";
import { ClassMetadata } from "ui5/antares/pro/types/Global.types";
import { Condition, Operator, PropertyRef, Settings, TimeObject } from "ui5/antares/pro/types/v2/validation/ValidationLogic.types";
import NavigationProperty from "ui5/antares/pro/v2/metadata/NavigationProperty";
import Factory from "ui5/antares/pro/v2/ui/Factory";
import TimeValidation from "ui5/antares/pro/v2/validation/TimeValidation";

/**
 * Defines business rule validations for a specific property of an entity during a Create or Update process.
 *
 * The **ValidationLogic** class is part of the UI5 Antares Pro library and enables developers to define advanced
 * validation rules that enforce **business constraints** during submission. A **ValidationLogic** instance must be
 * explicitly created and assigned to a property of an entity within the **CreateEntry** or **UpdateEntry** class.
 *
 * At runtime, the library automatically invokes all **ValidationLogic** instances right before submission. If a rule
 * fails, the submission process is halted and the user receives a validation message rendered as **valueStateText**
 * under the corresponding UI control generated by the library.
 *
 * ---
 *
 * ### 🔍 Types of Validation Supported
 *
 * #### 1. Format Validations *(Handled by the framework)*
 * These validations are always performed by default and ensure that the entered value matches the expected data
 * type and format, such as ensuring numbers, dates, and booleans are correctly structured. These are handled
 * through standard SAPUI5 OData types and do **not** require a **ValidationLogic** instance.
 *
 * #### 2. Business Rule Validations *(Handled via **ValidationLogic**)*
 * These validations capture **domain-specific rules** beyond basic formatting. They must be explicitly defined
 * using this class. Examples include:
 *
 * - A field must be greater than or equal to a certain value.
 * - Conditional rules like: "If field A equals 'ABC', then field B must equal 'XYZ'."
 * - Compound rules with logical operators (And, Or), such as:
 *   **"If field1 > 100 And field2 > 150, then field3 must be < 50."**
 *
 * ---
 *
 * ### ⚙️ Condition Structure and Operators
 *
 * A **ValidationLogic** instance can contain either:
 * - A **single condition**, or
 * - A group of **sub-conditions**, each bound by a logical operator (**And**, **Or**).
 *
 * Supported comparison operators include:
 * - **GT**, **GE**, **LT**, **LE**, **EQ**, **NE** (Greater/Less Than, Equal, Not Equal, etc.)
 * - **BT** (Between), **IN** (Array inclusion), **StartsWith**, **EndsWith**, and more.
 * - **"Regex"** operator for custom regular expression validation.
 *
 * When using the **"Regex"** operator, the consumer must provide a **RegExp** instance to **value1**.
 *
 * Additionally, the condition can compare a property’s value against:
 * - A **static value**
 * - Another **property’s value**
 *
 * ---
 *
 * ### ⏱ Special Handling for **Edm.Time**
 *
 * For properties with the type **Edm.Time**, the library requires a special format that includes hours, minutes,
 * and seconds. The consumer must use the **TimeValidation** class to represent values in these cases. For example:
 *
 * ```ts
 * const timeValue = new TimeValidation("01", "30", "00"); // 1 hour, 30 minutes, 0 seconds
 * logic.setValue1(timeValue);
 * ```
 *
 * ---
 *
 * ### 🧠 Custom Validator Function
 *
 * If the provided condition logic does not cover the required validation scenario, the consumer can attach a custom
 * validator function to the logic using **setValidator**. This function can be synchronous or asynchronous and receives
 * the value of the target property at runtime.
 *
 * - If it returns **true**, the value is considered valid.
 * - If it returns **false** (or a rejected promise), the submission is blocked and an error is shown.
 *
 * Example:
 * ```ts
 * logic.setValidator(async (value) => {
 *     const isAvailable = await checkBackendUniqueness(value);
 *     return isAvailable;
 * });
 * ```
 *
 * ---
 *
 * ### 🔄 Execution Lifecycle
 *
 * The library automatically evaluates all defined **ValidationLogic** instances when:
 * - The user submits a form or table
 * - A relevant field is modified and triggers revalidation
 *
 * If any rule fails:
 * - The process is aborted
 * - The corresponding control displays the error message
 * - Affected control receives a **ValueState** of **Error**
 *
 * ---
 *
 * ### 📌 Summary
 * - Format validation is built-in and always active.
 * - Business rules must be defined via **ValidationLogic**.
 * - You can use conditions, sub-conditions, and logical operators.
 * - Regex and property-to-property comparisons are supported.
 * - **Edm.Time** requires **TimeValidation** as a value wrapper.
 * - You may use custom validator functions for advanced needs.
 * 
 * @namespace ui5.antares.pro.v2.validation
 */
export default class ValidationLogic extends ManagedObject {
    static metadata: ClassMetadata = {
        library: "ui5.antares.pro",
        final: true,
        properties: {
            propertyName: { type: "string" },
            operator: { type: "string" },
            value1: { type: "any" },
            value2: { type: "any" },
            errorMessage: { type: "string" },
            logicalOperator: { type: "string", defaultValue: "And" },
            conditions: { type: "object[]", defaultValue: [] },
            validator: { type: "function" }
        }
    };

    constructor(settings: Settings) {
        super(settings as $ManagedObjectSettings);
    }

    /**
     * Evaluates the validation logic defined in this instance.
     * This method is automatically called by the library during the submission process.
     * 
     * It checks the provided conditions or runs the custom validator function,
     * depending on how the instance was configured. If the validation fails,
     * the corresponding error message is displayed under the field.
     * 
     * **Do not call this method manually.** It is handled internally by the UI5 Antares Pro library.
     * 
     * @internal
     */
    public async evaluate(value: any) {
        const validator = this.getValidator();
        const factory = this.getFactory();

        if (validator) {
            BusyIndicator.show(0);

            const result = await Promise.resolve(validator.call(factory.getController(), value));
            BusyIndicator.hide();

            if (!result) {
                throw new ValidateException(this.getErrorMessage());
            }

            return;
        }

        const valid = this.evaluateConditions();

        if (!valid) {
            return;
        }

        const value1 = this.getValue1();
        const value2 = this.getValue2();

        const evaluation = this.evaluateSingleCondition(
            this.getOperator(),
            value,
            this.isPropertyRef(value1) ? this.getPropertyRefValue(value1) : value1,
            this.isPropertyRef(value2) ? this.getPropertyRefValue(value2) : value2
        );

        if (!evaluation) {
            throw new ValidateException(this.getErrorMessage());
        }
    }

    private evaluateConditions() {
        if (!this.getConditions().length) {
            return true;
        }

        const evaluations: boolean[] = [];
        const context = this.getContext();

        for (const condition of this.getConditions()) {
            const contextValue = context.getProperty(this.getPropertyPath(condition.propertyName));
            const value1 = this.hasValue1(condition) ? condition.value1 : undefined;
            const value2 = this.hasValue2(condition) ? condition.value2 : undefined;

            const evaluation = this.evaluateSingleCondition(
                condition.operator,
                contextValue,
                this.isPropertyRef(value1) ? this.getPropertyRefValue(value1) : value1,
                this.isPropertyRef(value2) ? this.getPropertyRefValue(value2) : value2
            );

            evaluations.push(evaluation);
        }

        if (this.getLogicalOperator() === "And") {
            return evaluations.every(evaluation => evaluation === true);
        } else {
            return evaluations.some(evaluation => evaluation === true);
        }
    }

    private evaluateSingleCondition(operator: Operator, contextValue: any, value1: any, value2: any): boolean {
        switch (operator) {
            case "NE":
                return this.getCorrectedValue(contextValue) !== this.getCorrectedValue(value1);
            case "GE":
                return this.getCorrectedValue(contextValue) >= this.getCorrectedValue(value1);
            case "GT":
                return this.getCorrectedValue(contextValue) > this.getCorrectedValue(value1);
            case "LE":
                return this.getCorrectedValue(contextValue) <= this.getCorrectedValue(value1);
            case "LT":
                return this.getCorrectedValue(contextValue) < this.getCorrectedValue(value1);
            case "IsEmpty":
                return this.getCorrectedValue(contextValue) == null || this.getCorrectedValue(contextValue) === "";
            case "Contains":
                return (contextValue as string).includes(value1);
            case "NotContains":
                return (contextValue as string).includes(value1) === false;
            case "StartsWith":
                return (contextValue as string).startsWith(value1);
            case "NotStartsWith":
                return (contextValue as string).startsWith(value1) === false;
            case "EndsWith":
                return (contextValue as string).endsWith(value1);
            case "NotEndsWith":
                return (contextValue as string).endsWith(value1) === false;
            case "BT":
                return this.getCorrectedValue(contextValue) >= this.getCorrectedValue(value1) &&
                    this.getCorrectedValue(contextValue) <= this.getCorrectedValue(value2);
            case "NB":
                return this.getCorrectedValue(contextValue) > this.getCorrectedValue(value2) ||
                    this.getCorrectedValue(contextValue) < this.getCorrectedValue(value1);
            case "In":
                return value1.includes(contextValue);
            case "NotIn":
                return value1.includes(contextValue) === false;
            case "Regex":
                return (value1 as RegExp).test(contextValue as string);
            default:
                return this.getCorrectedValue(contextValue) === this.getCorrectedValue(value1);
        }
    }

    private getCorrectedValue(value: any) {
        if (value instanceof Date) {
            return value.getTime();
        } else if (value instanceof TimeValidation) {
            return value.getMilliseconds();
        } else if (this.isTimeObject(value)) {
            return value.ms;
        } else {
            return value;
        }
    }

    private getFactory() {
        const parent = this.getParent() as ManagedObject;

        if (parent.isA<NavigationProperty>("ui5.antares.pro.v2.metadata.NavigationProperty")) {
            return parent.getOwnerParent();
        }

        return parent as Factory;
    }

    private getContext() {
        const parent = this.getParent() as ManagedObject;

        if (parent.isA<NavigationProperty>("ui5.antares.pro.v2.metadata.NavigationProperty")) {
            return parent.getContext();
        }

        return (parent as Factory).getContext();
    }

    private getPropertyPath(property: string) {
        const parent = this.getParent() as ManagedObject;

        if (parent.isA<NavigationProperty>("ui5.antares.pro.v2.metadata.NavigationProperty")) {
            if (parent.getMultiplicity() === "One") {
                return parent.getName() + "/" + property;
            } else {
                return property;
            }
        }

        return property;
    }

    private hasValue1(condition: Condition): condition is Extract<Condition, { value1: any; }> {
        return "value1" in condition;
    }

    private hasValue2(condition: Condition): condition is Extract<Condition, { value2: any; }> {
        return "value2" in condition;
    }

    private isTimeObject(value: any): value is TimeObject {
        return typeof value === "object" &&
            value != null &&
            "ms" in value &&
            typeof value.ms === "number";
    }

    private isPropertyRef(value: any): value is PropertyRef {
        return typeof value === "object" &&
            value != null &&
            "propertyName" in value &&
            typeof value.propertyName === "string";
    }

    private getPropertyRefValue(propertyRef: PropertyRef) {
        const context = this.getContext();
        return context.getProperty(this.getPropertyPath(propertyRef.propertyName));
    }
}