import ManagedObject, { $ManagedObjectSettings } from "sap/ui/base/ManagedObject";
import { ClassMetadata } from "ui5/antares/pro/types/Global.types";
import { FormUtilityProvider } from "ui5/antares/pro/types/v2/core/BaseContext.types";
import { MetaContextOwner } from "ui5/antares/pro/types/v2/metadata/MetaContext.types";
import { Settings } from "ui5/antares/pro/types/v2/metadata/NavigationProperty.types";
import { Settings as TableGeneratorSettings } from "ui5/antares/pro/types/v2/ui/TableGeneratorBase.types";
import { Operation } from "ui5/antares/pro/types/v2/ui/Factory.types";
import MetaContext from "ui5/antares/pro/v2/metadata/MetaContext";
import Factory from "ui5/antares/pro/v2/ui/Factory";
import FormGeneratorBase from "ui5/antares/pro/v2/ui/FormGeneratorBase";
import GridTableGenerator from "ui5/antares/pro/v2/ui/GridTableGenerator";
import ResponsiveTableGenerator from "ui5/antares/pro/v2/ui/ResponsiveTableGenerator";
import SimpleFormGenerator from "ui5/antares/pro/v2/ui/SimpleFormGenerator";
import SmartFormGenerator from "ui5/antares/pro/v2/ui/SmartFormGenerator";
import TableGeneratorBase from "ui5/antares/pro/v2/ui/TableGeneratorBase";
import LibraryBundle from "ui5/antares/pro/v2/util/LibraryBundle";
import CustomElement from "ui5/antares/pro/v2/custom/CustomElement";
import CustomData from "sap/ui/core/CustomData";

/**
 * Configuration class used to define navigation properties (associations) within the **UI5 Antares Pro** library.
 *
 * The **NavigationProperty** class is intended to configure how associated entities should be rendered and processed
 * inside the dialogs or components that are generated by the library. It enables support for deep handling of
 * associations defined in the metadata of a given **EntitySet**, including both **1:1** and **1:N** cardinalities.
 *
 * ### Core Behavior:
 *
 * - **1:1 Associations**: A form is generated to represent the associated entity. Deep create operations are **not supported**
 *   for such associations due to limitations in the SAPUI5 framework.
 * - **1:N Associations**: A table is generated (either **sap.ui.table.Table** by default or **sap.m.Table** if configured),
 *   along with action buttons appropriate for the specific **Entry** class context.
 *
 * ### Generated Action Buttons:
 *
 * - **CreateEntry**: **Create** and **Delete** buttons are generated to allow child entities to be added or removed prior to submission.
 * - **UpdateEntry**: **Create**, **Update**, and **Delete** buttons are generated to enable full CRUD operations on associated entities.
 * - **DeleteEntry**: A **Delete** button is generated to remove existing associated records.
 * - **DisplayEntry**: A **Display** button is generated to allow read-only inspection of child entities in a dialog.
 *
 * ### Table Personalization:
 * - A settings button is generated for every table to allow personalization.
 * - By default, only 5 columns are shown; the rest are hidden.
 * - The default visible column count can be configured by the consumer.
 * - Column order and visibility can be adjusted by the end user at runtime.
 *
 * ### Advanced Configuration:
 * The following features can also be applied to navigation properties, similar to those of an **Entry**:
 * - **ValidationLogic**: Custom validation rules can be attached.
 * - **ValueList**: Value help configurations can be defined.
 * - **CustomElement**: Auto-generated controls can be replaced.
 * - **CustomContent**: Custom SAPUI5 content can be injected.
 * - **Field-level configuration**: Properties can be marked as **required**, **readonly**, **excluded**, and so on.
 *
 * ### Usage:
 * An instance of **ui5.antares.pro.v2.metadata.NavigationProperty** must be created with the name of the navigation
 * property as defined in the metadata. This name must match a valid association for the **EntitySet** configured
 * in the target **Entry** class. Once defined, it should be passed to the corresponding **Entry** class as an aggregation.
 * 
 * @namespace ui5.antares.pro.v2.metadata
 */
export default class NavigationProperty extends ManagedObject implements MetaContextOwner, FormUtilityProvider {
    static metadata: ClassMetadata = {
        library: "ui5.antares.pro",
        final: true,
        properties: {
            name: { type: "string" },
            index: { type: "int" },
            tableClass: { type: "string", defaultValue: "sap.ui.table.Table" },
            tableTitle: { type: "string" },
            tableLayoutData: { type: "object" },
            formTitle: { type: "string" },
            createDialogTitle: { type: "string" },
            updateDialogTitle: { type: "string" },
            deleteDialogTitle: { type: "string" },
            readDialogTitle: { type: "string" },
            createButtonText: { type: "string", defaultValue: LibraryBundle.getText("ui5AntaresPro.button.create") },
            createButtonType: { type: "string", defaultValue: "Emphasized" },
            updateButtonText: { type: "string", defaultValue: LibraryBundle.getText("ui5AntaresPro.button.update") },
            updateButtonType: { type: "string", defaultValue: "Emphasized" },
            deleteButtonText: { type: "string", defaultValue: LibraryBundle.getText("ui5AntaresPro.button.delete") },
            deleteButtonType: { type: "string", defaultValue: "Emphasized" },
            closeButtonText: { type: "string", defaultValue: LibraryBundle.getText("ui5AntaresPro.button.close") },
            closeButtonType: { type: "string", defaultValue: "Default" },
            visibleColumnCount: { type: "int", defaultValue: 5 },
            visibleRowCount: { type: "int", defaultValue: 5 },
            noEntryErrorEnabled: { type: "boolean", defaultValue: false },
            noEntryErrorMessage: { type: "string" },
            entitySet: { type: "string" },
            multiplicity: { type: "string" },
            context: { type: "object" },
            propertySettings: { type: "object[]", defaultValue: [] },
            propertyOrder: { type: "string[]", defaultValue: [] },
            inheritValues: { type: "object[]", defaultValue: [] },
            operation: { type: "string", visibility: "hidden" }
        },
        aggregations: {
            validationLogics: {
                type: "ui5.antares.pro.v2.validation.ValidationLogic",
                multiple: true,
                singularName: "validationLogic"
            },
            valueLists: {
                type: "ui5.antares.pro.v2.valuelist.ValueList",
                multiple: true,
                singularName: "valueList"
            },
            formLayout: {
                type: "ui5.antares.pro.v2.ui.FormLayout",
                multiple: false
            },
            customElements: {
                type: "ui5.antares.pro.v2.custom.CustomElement",
                multiple: true,
                singularName: "customElement"
            },
            customCells: {
                type: "ui5.antares.pro.v2.custom.CustomCell",
                multiple: true,
                singularName: "customCell"
            },
            customContents: {
                type: "ui5.antares.pro.v2.custom.CustomContent",
                multiple: true,
                singularName: "customContent"
            },
            metaContext: {
                type: "ui5.antares.pro.v2.metadata.MetaContext",
                multiple: false,
                visibility: "hidden"
            },
            formGenerator: {
                type: "ui5.antares.pro.v2.ui.FormGeneratorBase",
                multiple: false,
                visibility: "hidden"
            },
            tableGenerator: {
                type: "ui5.antares.pro.v2.ui.TableGeneratorBase",
                multiple: false,
                visibility: "hidden"
            }
        }
    };

    constructor(settings: Settings) {
        super(settings as $ManagedObjectSettings);
        this.setMetaContext(new MetaContext());
    }

    /**
     * Loads metadata required to determine the properties of the target entity
     * and the multiplicity of the navigation property.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public async load() {
        const parent = this.getOwnerParent();
        const navigationInfo = await MetaContext.getNavigationInfo(parent.getODataModel(), parent.getEntitySet(), this.getName());

        this.setEntitySet(navigationInfo.entitySet);
        this.setMultiplicity(navigationInfo.multiplicity);
        this.setOperation(this.getOwnerParent().getOperation());
        await this.getMetaContext().load();

        if (navigationInfo.multiplicity === "One") {
            if (this.getOwnerParent().getOperation() === "Create") {
                throw new Error("Cannot create entity; deep create on navigation property '"
                    + this.getName() + "' with single cardinality is not supported (not supported by standard SAPUI5 Library)");
            }

            this.setContext(parent.getContext());
        }
    }

    /**
     * Generates the UI form or table based on the multiplicity determined by the **load** method.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public async generate() {
        if (this.getMultiplicity() === "One") {
            if (this.getOwnerParent().getFormType() === "SimpleForm") {
                this.setFormGenerator(new SimpleFormGenerator());
            } else {
                this.setFormGenerator(new SmartFormGenerator());
            }

            this.getFormGenerator().generate();
        } else {
            if (this.getTableClass() === "sap.m.Table") {
                this.setTableGenerator(new ResponsiveTableGenerator(this.getTableGeneratorSettings()));
            } else {
                this.setTableGenerator(new GridTableGenerator(this.getTableGeneratorSettings()));
            }

            await this.getTableGenerator().generate();
        }
    }

    /**
     * Returns the UI content generated by this NavigationProperty instance.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public getContent() {
        if (this.getMultiplicity() === "One") {
            return this.getFormGenerator().getForm();
        } else {
            return this.getTableGenerator().getContent();
        }
    }

    /**
     * Returns the parent object that owns this NavigationProperty instance.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public getOwnerParent() {
        return this.getParent() as Factory;
    }

    /**
     * Returns the MetaContext instance loaded and associated with this NavigationProperty.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public getMetaContext() {
        return this.getAggregation("metaContext") as MetaContext;
    }

    /**
     * Returns the current operation type of this NavigationProperty instance,
     * which can be one of Create, Update, Delete, or Read.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public getOperation() {
        return this.getProperty("operation") as Operation;
    }

    /**
     * Sets the current operation (Create, Update, Delete, or Read) for the NavigationProperty.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @param operation - The operation to set.
     * @internal
     */
    public setOperation(operation: Operation) {
        this.setProperty("operation", operation);
    }

    /**
     * Retrieves the validation logic object associated with a specific property.
     *
     * @param property - The name of the property to find the validation logic for.
     * @returns The ValidationLogic instance related to the given property, or undefined if none is found.
     */
    public getValidationLogicByProperty(property: string) {
        return this.getValidationLogics().find(logic => logic.getPropertyName() === property);
    }

    /**
     * Retrieves the value list (value help) configuration associated with a specific property.
     *
     * @param property - The name of the property to find the value list for.
     * @returns The ValueList instance related to the given property, or undefined if none is found.
     */
    public getValueListByProperty(property: string) {
        return this.getValueLists().find(valueList => valueList.getLocalDataProperty() === property);
    }

    /**
     * Retrieves the CustomCell instance associated with the specified property name.
     * 
     * Searches the aggregated CustomCell instances and returns the first one
     * whose **propertyName** matches the given parameter.
     * 
     * @param property - The name of the property to find the corresponding CustomCell for.
     * @returns The matching CustomCell instance if found; otherwise, undefined.
     */
    public getCustomCellByProperty(property: string) {
        return this.getCustomCells().find(cell => cell.getPropertyName() === property);
    }

    /**
     * Called internally by the library before submission to validate that all
     * validation logics and formats are correct.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public async validate() {
        if (this.getMultiplicity() === "Many") {
            throw new Error("NavigationProperty validate method can only be used for navigations with multiplicity: One.");
        }

        return this.getFormGenerator().validate();
    }

    /**
     * Checks if any entries have been added to the table of a navigation property
     * with **many** cardinality when the **noEntryErrorEnabled** option is set.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public hasNoEntryError() {
        if (this.getMultiplicity() === "One") {
            return false;
        }

        return this.getTableGenerator().getCount() === 0;
    }

    /**
     * Deregisters personalization (p13n) configurations of the generated tables.
     * This method is used internally by the library.
     *
     * **This method is intended for internal use only and must NOT be called by consumers.**
     *
     * @internal
     */
    public deregisterP13n() {
        if (this.getMultiplicity() === "Many") {
            this.getTableGenerator().deregisterP13n();
        }
    }

    /**
     * Adds a CustomElement instance, which represents a custom UI control replacing 
     * default controls generated for specific properties.
     * 
     * @param customElement - The CustomElement to be added.
     */
    public addCustomElement(customElement: CustomElement) {
        customElement.getElement().addCustomData(new CustomData({
            key: "UI5AntaresProControlType",
            value: "Custom"
        }));

        customElement.getElement().addCustomData(new CustomData({
            key: "UI5AntaresProPropertyName",
            value: customElement.getPropertyName()
        }));

        this.addAggregation("customElements", customElement);
    }

    /**
     * Retrieves the custom UI control element associated with a specific property.
     *
     * @param property - The name of the property to find the custom element for.
     * @returns The CustomElement instance related to the given property, or undefined if none is found.
     */
    public getCustomElementByProperty(property: string) {
        return this.getCustomElements().find(element => element.getPropertyName() === property);
    }

    private setMetaContext(metaContext: MetaContext) {
        this.setAggregation("metaContext", metaContext);
    }

    private getFormGenerator() {
        return this.getAggregation("formGenerator") as FormGeneratorBase;
    }

    private setFormGenerator(formGenerator: FormGeneratorBase) {
        this.setAggregation("formGenerator", formGenerator);
    }

    private getTableGenerator() {
        return this.getAggregation("tableGenerator") as TableGeneratorBase;
    }

    private setTableGenerator(tableGenerator: TableGeneratorBase) {
        this.setAggregation("tableGenerator", tableGenerator);
    }

    private getTableGeneratorSettings() {
        const settings: TableGeneratorSettings = {
            tableTitle: this.getTableTitle(),
            createDialogTitle: this.getCreateDialogTitle(),
            updateDialogTitle: this.getUpdateDialogTitle(),
            deleteDialogTitle: this.getDeleteDialogTitle(),
            readDialogTitle: this.getReadDialogTitle(),
            createButtonText: this.getCreateButtonText(),
            createButtonType: this.getCreateButtonType(),
            updateButtonText: this.getUpdateButtonText(),
            updateButtonType: this.getUpdateButtonType(),
            deleteButtonText: this.getDeleteButtonText(),
            deleteButtonType: this.getDeleteButtonType(),
            closeButtonText: this.getCloseButtonText(),
            closeButtonType: this.getCloseButtonType(),
            visibleColumnCount: this.getVisibleColumnCount(),
            visibleRowCount: this.getVisibleRowCount()
        };

        return settings;
    }
}